{{- if and .Values.ingressTCP.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-ingressroutetcp
  namespace: {{ .Release.Namespace | quote }}    
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: redb
      containers:
      - name: patch-ingressroutetcp
        image: "bitnami/kubectl:latest"
        command:
         - "bin/bash"
         - "-c"
         - |
           while true
           do
             kubectl get redb {{ .Values.databaseName }}|grep active && break
             sleep 10
           done
           PORT=$(kubectl get redb {{ .Values.databaseName }} -o jsonpath="{.status.internalEndpoints..port}")
           echo $PORT
           kubectl patch ingressroutetcp redb-external-access --type='json' -p='[{"op": "replace", "path": "/spec/routes/0/services/0/port", "value":'${PORT}'}]'
{{- end }}