apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redb-delete
  namespace: {{ .Release.Namespace | quote }} 
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  resourceNames: [{{ .Release.Namespace }}]
  verbs: ["get", "patch"]
- apiGroups: 
    - traefik.containo.us
  resources: ["ingressroutetcps"]
  verbs: ["delete", "get", "list", "patch", "create", "update", "watch"]  
- apiGroups:
    - app.redislabs.com
  resources: ["redisenterprisedatabases"]
  verbs: ["delete", "get", "list", "patch", "create", "update", "watch"]  