{{- if and .Values.backup.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: secret-s3
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  # annotations:
  #   "helm.sh/hook": pre-install
  #   "helm.sh/hook-delete-policy": hook-succeeded    
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.backup.accesskeyid }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backup.secretkey }}
{{- end }}